name: Deploy docs to Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "docs/requirements.txt"
      - name: Build Python
        working-directory: python
        run: |
          python -m pip install -e .
          python -m pip install -r ../docs/requirements.txt
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: node/package-lock.json
      - uses: Swatinem/rust-cache@v2
      - name: Install node dependencies
        working-directory: node
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libssl-dev
      - name: Build node
        working-directory: node
        run: |
          npm ci
          npm run build
          npm run tsc
      - name: Create markdown files
        working-directory: node
        run: |
          npx typedoc --plugin typedoc-plugin-markdown --out ../docs/src/javascript src/index.ts
      - name: Build docs
        run: |
          PYTHONPATH=. mkdocs build -f docs/mkdocs.yml
      - name: Broken Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          # Check all markdown and html files in repo. Ignores the following status codes to reduce false positives:
          #   - 403(OpenVINO, "forbidden")
          #   - 429(Instagram, "too many requests")
          #   - 500(Zenodo, "cached")
          #   - 502(Zenodo, "bad gateway")
          #   - 999(LinkedIn, "unknown status code")
          args: |
            --accept 403,429,500,502,999
            --exclude-loopback
            --exclude "https?://(www\.)?(github\.com|linkedin\.com|twitter\.com|instagram\.com|kaggle\.com|fonts\.gstatic\.com|url\.com)"
            --scheme https
            "./**/*.md"
            "./**/*.html"
          token: ${{ secrets.LANCEDB_RELEASE_TOKEN }}
          output: ../lychee/results.md
          fail: true
        continue-on-error: false
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs/site"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1